#!/usr/bin/env bash
# This script will configure nginx
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx start
sudo sed -i '24i\       rewrite ^/redirect_me https://www.google.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
