#!/usr/bin/env bash
# install and setup nginx web server
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo sed -i '24i\       rewrite ^/redirect_me https://www.google.com/ permanent;' /etc/nginx/sites-enabled/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error_404.html
sudo sed -i '25i\	error_page 404 /error_404.html;' /etc/nginx/sites-enabled/default
CONFIG="\\\n\tadd_header X-Served-By "$(hostname)";"
sudo sed -i "24i $CONFIG" /etc/nginx/sites-enabled/default
sudo service nginx start
