#!/usr/bin/env bash
#Thsi script To infinity and beyond indefinitely
#With a sleep 2 in between each iteration
#I am invincible!!! when receiving a SIGTERM signal
num=0
while [ $num -eq 0 ]; do
	echo "To infinity and beyond"
	sleep 2
done
trap 'echo "I am invincible!!!"' SIGTERM
