#!/usr/bin/env bash
#This script displays numbers from 1 to 100.
for ((num=1; num <= 100; num++)); do
	if [ $((num%3)) -eq 0 ] && [ $((num%5)) -eq 0 ]; then
		echo "FizzBuzz"
	fi
	if [ $((num%3)) -eq 0 ] && [ $((num%5)) -ne 0 ]; then
		echo "Fizz"
	fi
	if [ $((num%5)) -eq 0 ] && [ $((num%3)) -ne 0 ]; then
		echo "Buzz"
	else
		echo $num
	fi
done
